### ISSUE TITLE
napalm_yang does not set the admin-status correct

### ISSUE THREAD

**Issue by misch42** [napalm-automation/napalm-yang#166]
Hi,

I use salt with an openconfig model to configure my juniper switch. With:
openconfig_interfaces_cfg:
  interfaces:
    interface:
      ge-0/0/6:
        config:
          description: "new description example"
          enabled: false

the command salt myswitch state.apply switch.interfaces takes down the interface correctly.

Changing the last line to "enabled: True" does NOT enable the interface again.

Ideas?

Michael

**Comment by misch42** [comment]
Update: When I use net.load_config setting the status to enabled / disabled, it works:
salt switch03 net.load_config text='interfaces { ge0/0/6 { enable; } }' -> Interface enabled again.

**Comment by misch42** [comment]
oh, my state is:
{%- set expected_config =  pillar.get('openconfig_interfaces_cfg') -%}
interfaces_config:
  napalm_yang.managed:
    - data: {{ expected_config | json }}
    - models:
      - models.openconfig_interfaces
    - debug: true

**Comment by dbarrosop** [comment]
Hello,
I am afraid I don't know anything about salt or its napalm-yang integration. If you can replicate the issue directly with code I will look into it, otherwise, I'd suggest talking with the maintainers of that integration.

I am going to be closing this issue but feel free to reopen providing a snippet of code reproducing it.

Thanks
